language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: dependencies=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

before_script:
  - travis_retry composer install --no-interaction
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/phpunit
  - vendor/bin/behat -fprogress
