framework:
    secret:                           "sroze.io"
    router:
        resource:                     "%kernel.root_dir%/config/routing.yml"
        strict_requirements:          "%kernel.debug%"
    trusted_proxies: ~
    test: ~
    session:
        storage_id:                    "session.storage.mock_file"

tolerance:
    operation_runners:
        default:
            retry:
                runner:
                    callback: ~

                waiter:
                    count_limited:
                        count: 10
                        waiter:
                            exponential_back_off:
                                exponent: 1
                                waiter:
                                    'null': ~

    aop: ~
